### ISSUE TITLE
Integration with GLPI 0.90.1 + WebServices 1.6.0

### ISSUE THREAD

**Issue by johnk3r** [janssenlima/zabbix-glpi#1]
The following error message in time to run the PHP command:

zabbix:/usr/share/zabbix/glpi # php /usr/share/zabbix/glpi/tickets_zabbix_glpi.php eventhost="Zabbix server" event="DOWN" state="PROBLEM" hostproblemid=0 lasthostproblemid=0 servico="Zabbix server VPN DOWN" triggerid="16039" eventzabbix="4131285"
- Calling 'glpi.test' on http://10.1.1.249/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.doLogin' on http://10.1.1.249/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.createTicket' on http://10.1.1.249/glpi/plugins/webservices/xmlrpc.php?session=3fa69uvfaedfppmjluu4rbkgq7
  xmlrpc error(16): Command not allowed
  Traceback (most recent call last):
  File "/usr/share/zabbix/glpi/ack_zabbix_glpi.py", line 15, in <module>
    reconhecer_evento = conexao.event.acknowledge({"eventids": sys.argv[1], "message": "Ticket " + str(sys.argv[2]) + " criado no GLPI."})
  IndexError: list index out of range
- Calling 'glpi.doLogout' on http://10.1.1.249/glpi/plugins/webservices/xmlrpc.php?session=3fa69uvfaedfppmjluu4rbkgq7

**Comment by johnk3r** [comment]
Problem solved. Permission error in GLPI.

**Comment by fran7ik** [comment]
Hello, same problem, can describe what permissions you've changed.
