### ISSUE TITLE
Issue in Zabbix opening ticket in GLPI

### ISSUE THREAD

**Issue by pkapp67** [janssenlima/zabbix-glpi#10]
Hello everyone, 

I got a small issue with the opening / closing ticket in Zabbix.

It seems that my Zabbix is able to connect to the GLPI (i can see it in the GLPI logs), the action is marked as executed in the Zabbix dashboard but i can't see anything in the ticket section.

I tried to launch the script manually from the shell with the command : 

php tickets_zabbix_glpi.php eventhost="server" event="DOWN" state="PROBLEM" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"

And it returns me only :

+ Calling 'glpi.test' on http://X.X.X.X/glpi/plugins/webservices/xmlrpc.php

Can anyone help me debugging this ? 
Thank you in advance for your help

Zabbix Version : 3.0.3 on Debian
GLPI Version : 0.90.3 on Debian - WebServices 1.6.0

**Comment by Floots** [comment]
Hello,
I've exactly the same problem than you. 
Did you find an issue in your case?
Thank's a lot for your answer
