### ISSUE TITLE
Problema integração GLPI 0.85.5 + Zabbix 3.2.3

### ISSUE THREAD

**Issue by ghost** [janssenlima/zabbix-glpi#12]
[root@localhost scripts_externos]# php /etc/zabbix/web/scripts_externos/tickets_zabbix_glpi.php
+ Calling 'glpi.test' on http://10.0.13.16/var/www/html/glpi/plugins/webservices/xmlrpc.php
PHP Warning:  file_get_contents(http://10.0.13.16/var/www/html/glpi/plugins/webservices/xmlrpc.php): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /etc/zabbix/web/scripts_externos/tickets_zabbix_glpi.php on line 80
+ No response
[root@localhost scripts_externos]#

**Comment by stdonato** [comment]
Estou enfrentando o mesmo problema.
