### ISSUE TITLE
Não esta criando Ticket

### ISSUE THREAD

**Issue by jeaneduardo** [janssenlima/zabbix-glpi#14]
Olá boa tarde

Segui o tutorial  http://janssenlima.blogspot.com.br/2013/11/integracao-zabbix-glpi.html para fazer a instalação porem o ticket não é aberto, vou detalhar abaixo o procedimento.

Ambiente
GLPI 9.1.2
Debian GNU/Linux 8
PHP 5.6.30
Apache/2.4.10

Zabbix 3.2
Debian GNU/Linux 9
PHP 7.0.14-2 
Apache/2.4.25

**Instalação do webservices**
1. Instalei o plugin webservices e configurei para o IP Do zabbix ter acesso a ele.
![captura de tela de 2017-03-07 12-50-31](https://cloud.githubusercontent.com/assets/8227475/23664615/d00c7e98-0334-11e7-88db-2a6a20cdd66a.png)

**Instalação integração Zabbix** 
1. Coloquei os arquivos dentro da pasta do zabbix /usr/local/share/zabbix/externalscripts com permissão de execução
zabbix zabbix  559 mar  3 14:54 ack_zabbix_glpi.py
zabbix zabbix 7632 mar  7 12:29 tickets_zabbix_glpi.php

2. No arquivo tickets_zabbix_glpi.php configurei da seguinte forma
$user =         "USUARIO_GLPI";
$password =     "SENHA_GLPI";
$xmlhost =      "HOST_GLPI";
$xmlurl =       "plugins/webservices/xmlrpc.php";
$category =     "";
$watcher =      "2";
$watchergroup = "1";
$sqlhost =      "HOST_BD_GLPI";
$sqldb =        "glpi";
$sqluser =      "USUÁRIO_BD_GLPI";
$sqlpwd =       "SENHA_BD_GLPI";
$path_zabbix =  "/usr/local/share/zabbix/externalscripts";

3. Configurei ação no Zabbix conforme imagens abaixo.
![captura de tela de 2017-03-07 12-45-01](https://cloud.githubusercontent.com/assets/8227475/23664361/225ef2e4-0334-11e7-98f6-60de8df4ef50.png)
![captura de tela de 2017-03-07 12-45-08](https://cloud.githubusercontent.com/assets/8227475/23664363/22627a2c-0334-11e7-9076-d7fbb91f9242.png)
![captura de tela de 2017-03-07 12-45-45](https://cloud.githubusercontent.com/assets/8227475/23664362/22628788-0334-11e7-93b5-9db0fc625078.png)
![captura de tela de 2017-03-07 12-46-00](https://cloud.githubusercontent.com/assets/8227475/23664364/22687ca6-0334-11e7-949e-f391ad4260d9.png)

Cenário
Quando acontece um desastre deveria abrir a notificação

1. Log do apache do GLPI
172.16.170.15 - - [07/Mar/2017:12:32:56 -0300] "POST /plugins/webservices/xmlrpc.php HTTP/1.0" 200 892 "-" "-"
172.16.170.15 - - [07/Mar/2017:12:32:56 -0300] "POST /plugins/webservices/xmlrpc.php HTTP/1.0" 200 1219 "-" "-"
172.16.170.15 - - [07/Mar/2017:12:32:57 -0300] "POST /plugins/webservices/xmlrpc.php?session=ru6sm24g3eeimn7njqjo5huak6 HTTP/1.0" 200 734 "-" "-"

2. Log do webservice GLPI
![captura de tela de 2017-03-07 12-50-08](https://cloud.githubusercontent.com/assets/8227475/23664561/a2678848-0334-11e7-9dff-9bc8ce152fdb.png)

Poderia me ajudar por favor

**Comment by GuiBalestro** [comment]
Jean, estou com a mesma situação que a sua.
Conseguistes descobrir o que faltou configurar para a geração do Ticket?

Vlw

**Comment by jeaneduardo** [comment]
Olá @GuiBalestro não consegui resolver, creio que seja um bug do plugin, estou aguardando alguma mensagem do desenvolvedor @janssenlima.

**Comment by GuiBalestro** [comment]
Boa noite @jeaneduardo ,
Essa forma de configuração é incompatível com a versão 9.1.2 do GLPI.
Na versão 9.1.2 existe API nativa no GLPI.
Eu fiz a integração usando o Verdanatech.
Tutorial nesse vídeo:

https://www.youtube.com/watch?v=BPK8tDj2yK0

**Comment by janssenlima** [comment]
Issue no github é usado para contribuição de código e report de bugs encontrados, não para suporte.
Contribuem com erros, não com pedido de ajuda.

**Comment by jeaneduardo** [comment]
@janssenlima foi reportado como bug e não como solicitação de suporte. O quesito no final do ticket "Poderia me ajudar por favor" é com a intenção de ter um possível bug e que pudessemos corrigir juntos, de tal forma que postei LOGs e todo instalação que fiz para simular erro já que a versão do zabbix utilizada é nova e poderia ter alguma incompatibilidade. Agora se você entendeu de outra forma infelizmente....

@GuiBalestro Obrigado pela atenção vou fazer conforme você postou
