### ISSUE TITLE
Acentuação no chamado criado pelo Zabbix

### ISSUE THREAD

**Issue by eduardo-fj** [janssenlima/zabbix-glpi#15]
Olá,

Estou tendo um problema de acentuação nos chamados criados pelo Zabbix, eles estão saindo da forma abaixo:
Monitoramento detectou a recuperaÃ§Ã£o do erro

Tanto no Zabbix e GLPI, se digitar com acentuação funciona
Poderia me ajudar?

**Comment by avinhaes** [comment]
Boa tarde.

Também tenho o mesmo problema. Alguém teria a solução ? Não consegui de jeito algum.


Muito obg.
