### ISSUE TITLE
Issue in Zabbix-GLPI integration using API

### ISSUE THREAD

**Issue by saumyajit** [janssenlima/zabbix-glpi#2]
Hi Janseen,

I want to setup Zabbix Monitoring tool along with GLPI as Service Desk
I've gone through your article regarding Zabbix-GLPI integration & I've followed the same steps. But ​no ticket got generated in GLPI, though Zabbix 'Action' is showing 'Ok'. I'm getting below output while running the action contain in CLI
​. PFB for the details. Kindly check & suggest where modification need to be done so that it'll work.​ Kindly let me know if you required more details. Thank you :)

---

[root@ZBX-GLPI-NMS externalscripts]# pwd
/usr/lib/zabbix/externalscripts
[root@ZBX-GLPI-NMS externalscripts]#
[root@ZBX-GLPI-NMS externalscripts]# php tickets_zabbix_glpi.php eventhost = "{HOSTNAME}" event = "DOWN" state = "{} TRIGGER.STATUS" hostproblemid = 0 lasthostproblemid =o servico = "{} TRIGGER.NAME" triggerid = "{} TRIGGER.ID" eventzabbix = "{} EVENT.ID"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.doLogin' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
  PHP Warning:  mysql_connect(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php on line 121
- Calling 'glpi.addTicketFollowup' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=1uopufppsiidhq8ndneeku1ge1
  **xmlrpc error(14): Bad parameter (ticket)**
- Calling 'glpi.doLogout' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=1uopufppsiidhq8ndneeku1ge1
  [root@ZBX-GLPI-NMS externalscripts]#
  ​********************************************************************************************************************
###### ######## Zabbix Server

IP: 192.168.233.139
OS:- CentOS 6.6 64bit
Zabbix Version:- 2.4.7
PHP Version:- 5.3.3
Python Version:- 2.6.6
Python-PIP Version:- 8.1.1
MariaDB Version:- mysql  Ver 15.1 Distrib 10.1.9-MariaDB,
###### ######## GLPI Server

IP: 192.168.233.140
OS:- CentOS 6.6 64bit
GLPI Version:- 0.85.5
Web Service Version:- 1.60.0
PHP Version:- 5.3.3
Python Version:- 2.6.6
MariaDB Version:- mysql  Ver 15.1 Distrib 10.1.9-MariaDB,
​​----------------------------------------------------------------------------------------------------------------------------------------

![ack_zabbix_glpi py configuration](https://cloud.githubusercontent.com/assets/18307963/14317811/9c36e0fa-fc27-11e5-98a3-385f7e316211.png)
![glpi ticket gui](https://cloud.githubusercontent.com/assets/18307963/14317810/9c35f226-fc27-11e5-9a07-a748ea3c3805.png)
![glpi webservice history](https://cloud.githubusercontent.com/assets/18307963/14317812/9c374e96-fc27-11e5-9075-2b46d3f6bac0.png)
![webservice configuration](https://cloud.githubusercontent.com/assets/18307963/14317813/9c392cac-fc27-11e5-94c2-d58def150ce9.png)
![webservice directory permission](https://cloud.githubusercontent.com/assets/18307963/14317819/9d2cfd5a-fc27-11e5-9c6e-f6e5a7f39cdd.png)
![zabbix event](https://cloud.githubusercontent.com/assets/18307963/14317814/9c3d3c0c-fc27-11e5-9353-8b8bb8166c34.png)
![zabbix action configuration_operation](https://cloud.githubusercontent.com/assets/18307963/14317815/9c6326c4-fc27-11e5-9201-ff537ba5beba.png)
![zabbix action configuration_condition](https://cloud.githubusercontent.com/assets/18307963/14317818/9ce393ea-fc27-11e5-9e4d-0598bf7d656b.png)
![zabbix action configuration_action](https://cloud.githubusercontent.com/assets/18307963/14317816/9c63d254-fc27-11e5-8cb3-f819e8abf354.png)
![tickets_zabbix_glpi php configuration](https://cloud.githubusercontent.com/assets/18307963/14317817/9c65a19c-fc27-11e5-9c72-321d4d59859c.png)

**Comment by janssenlima** [comment]
The macros in the command are wrong.
The correct command should be in this pattern:
`/opt/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="{HOSTNAME}" event="UP" state="{TRIGGER.STATUS}" hostproblemid=1 lasthostproblemid=1 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"`

But for you to run the php command in the terminal, you have to replace the macros for valid values.

Ex.:
`/opt/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="server" event="DOWN" state="PROBLEM" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"`

run the above command and verify that a ticket was generated in GLPI

any questions, please read the following [article](http://janssenlima.blogspot.com.br/2013/11/integracao-zabbix-glpi.html)

**Comment by saumyajit** [comment]
Hi,

## i'm getting below error while executing the command

[root@ZBX-GLPI-NMS externalscripts]# php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="{HOST.NAME}" event="UP" state="{TRIGGER.STATUS}" hostproblemid=1 lasthostproblemid=1 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
  PHP Fatal error:  Call to undefined function xmlrpc_encode_request() in /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php on line 75

## [root@ZBX-GLPI-NMS externalscripts]#

[root@ZBX-GLPI-NMS externalscripts]# php tickets_zabbix_glpi.php eventhost="server" event="UP" state="DOWN" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
  PHP Fatal error:  Call to undefined function xmlrpc_encode_request() in /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php on line 75

## [root@ZBX-GLPI-NMS externalscripts]#

**Comment by janssenlima** [comment]
Try this:

`/opt/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="server" event="DOWN" state="PROBLEM" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"`

**Comment by saumyajit** [comment]
I've checked the xmlrpc.ini & restarted httpd. after that "PHP Fatal error: Call to undefined function xmlrpc_encode_request()" error got rectified, But  still ticket not generated in GLPI & getting below output

[root@ZBX-GLPI-NMS externalscripts]# php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="server" **event="DOWN" state="PROBLEM**" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
  [root@ZBX-GLPI-NMS externalscripts]#

[root@ZBX-GLPI-NMS externalscripts]#php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="server" **event="UP" state="PROBLEM**" hostproblemid=1 lasthostproblemid=1 servico="Service httpd is down" triggerid="12345" eventzabbix="53"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.doLogin' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.addTicketFollowup' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=qd0g8mpv38hbiqf27ilfi2ivd4
  xmlrpc error(14): Bad parameter (ticket)
- Calling 'glpi.doLogout' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=qd0g8mpv38hbiqf27ilfi2ivd4

**Comment by janssenlima** [comment]
Try:

`php /var/www/html/glpi/plugins/webservices/scripts/examplesoap.php`

This script this script is that you return multiple records, no errors occur. You will see the calls being executed.

If it goes wrong you are having trouble installing the plugin webservices, or is missing a package.

**Comment by saumyajit** [comment]
Got below output after running the mentioned command, but sorry... could understand the use of it.

[root@GLPI-Ticketing webservices]# php /var/www/html/glpi/plugins/webservices/scripts/examplesoap.php
- Calling glpi.doLogin on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.createObjects on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.doLogout on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.doLogin on http://localhost//glpi/plugins/webservices/soap.php
  PHP Notice:  Undefined variable: profile in /var/www/html/glpi/plugins/webservices/scripts/examplesoap.php on line 225
- Calling glpi.createObjects on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.createObjects on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.createObjects on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.doLogout on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.doLogin on http://localhost//glpi/plugins/webservices/soap.php
- Calling glpi.getObject on http://localhost//glpi/plugins/webservices/soap.php
  Array
  (
  [name] => WSOAP_Computer_01_TESTING
  [id] => 1
  [locations_id] => 0
  [computertypes_id] => 0
  [computermodels_id] => 0
  [states_id] => 0
  [operatingsystems_id] => 0
  [operatingsystemversions_id] => 0
  [operatingsystemservicepacks_id] => 0
  [autoupdatesystems_id] => 0
  [serial] => I98GFD-FF98-F0ZFDF8-980
  [otherserial] => 0000134
  [users_id] => 6
  [groups_id] => 1
  [date_mod] => 2016-04-07 16:14:08
  [networks_id] => 0
  [domains_id] => 0
  [manufacturers_id] => 0
  [users_id_tech] => 0
  [groups_id_tech] => 0
  [entities_id] => 1
  [Monitor] => Array
      (
          [1] => Array
              (
                  [name] => WSOAP_Monitor_01_TESTING
                  [id] => 1
                  [locations_id] => 0
                  [monitortypes_id] => 0
                  [monitormodels_id] => 0
                  [states_id] => 0
                  [serial] => I98GFD-8973987-DE98
                  [otherserial] => 0000190
                  [users_id] => 6
                  [groups_id] => 1
                  [date_mod] => 2016-04-07 16:14:08
                  [size] => 0
                  [have_micro] => 0
                  [have_speaker] => 0
                  [have_subd] => 0
                  [have_bnc] => 0
                  [have_dvi] => 0
                  [have_pivot] => 0
                  [have_hdmi] => 0
                  [have_displayport] => 0
                  [manufacturers_id] => 0
                  [users_id_tech] => 0
                  [groups_id_tech] => 0
                  [entities_id] => 1
                  [is_global] => 0
              )
  
  ```
  )
  ```

)
- Calling glpi.doLogout on http://localhost//glpi/plugins/webservices/soap.php
  [root@GLPI-Ticketing webservices]# 
  *************************************************
  I've done some modification (PFB) & now Tickets are generating in GLPI, but macros value are not printing & getting an error (highlighted in bold) Kindly suggest

[root@ZBX-GLPI-NMS scripts]# php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="{HOST.NAME}" event="DOWN" state="PROBLEM" hostproblemid=0 lasthostproblemid=0 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"
- Calling 'glpi.test' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.doLogin' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.createTicket' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=7i7v8pb88alt9qgjroiupdqq60
  PHP Warning:  mysql_connect(): Headers and client library minor version mismatch. Headers:50173 Library:50312 in /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php on line 223
  Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/ack_zabbix_glpi.py", line 17, in <module>
    reconhecer_evento = conexao.event.acknowledge({"eventids": sys.argv[1], "message": "Ticket " + str(sys.argv[2]) + " criado no GLPI."})
  File "/usr/lib/python2.6/site-packages/zabbix_api.py", line 314, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/lib/python2.6/site-packages/zabbix_api.py", line 71, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/lib/python2.6/site-packages/zabbix_api.py", line 321, in do_request
    return self.parent.do_request(req)
  File "/usr/lib/python2.6/site-packages/zabbix_api.py", line 272, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
  **zabbix_api.ZabbixAPIException: (u'Error -32500: Application error., No permissions to referred object or it does not exist! while sending {"params": {"message": "Ticket 1 criado no GLPI.", "eventids": "{EVENT.ID}"}, "jsonrpc": "2.0", "method": "event.acknowledge", "auth": "e4b4169d19666b21bdf5ba942424f39e", "id": 1}', -32500)**
- Calling 'glpi.doLogout' on http://192.168.233.140/glpi/plugins/webservices/xmlrpc.php?session=7i7v8pb88alt9qgjroiupdqq60
  [root@ZBX-GLPI-NMS scripts]#

![screenshot from 2016-04-07 16 24 22](https://cloud.githubusercontent.com/assets/18307963/14348942/3ca79af6-fcdd-11e5-9b46-805b5875c4c0.png)

**Comment by janssenlima** [comment]
Your problem is that when you execute the command in the shell, you should replace the macros for valid values. That's what makes Zabbix to run the command automatically.

Do this:
In action to create the ticket, you enter the following command:

`php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php  eventhost="{HOSTNAME}" event="DOWN" state="{TRIGGER.STATUS}" hostproblemid=0 lasthostproblemid=0 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"`

and in action to close the ticket, you enter the following command:

`php /usr/lib/zabbix/externalscripts/tickets_zabbix_glpi.php  eventhost="{HOSTNAME}" event="UP" state="{TRIGGER.STATUS}" hostproblemid=1 lasthostproblemid=1 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"`

It is enough to work, since it is now opening the ticket in GLPI.

**Comment by carlosferreira1** [comment]
Olá Janssen,
Estou utilizando o Centos 7 com Zabbix 3.0 e o GLPI na versão 0.9.
Os tickets são abertos corretamente no GLPI, porém o mesmo não fecha. 

Quando executo o comando na mão, o chamado é fechado. Observe que na hora de abrir ele gera um erro, mas mesmo assim, ele abre o chamado no GLPI.
Outro detalhe, se eu colocar o STATUS como OK na mão ele não fecha o chamado. Só fecha se eu colocar o status como SOLVED.

ABRINDO O CHAMADO
-------------------------------------
[root@srvzabbixsina externalscripts]# php tickets_zabbix_glpi.php eventhost="Zabbix server" event="DOWN" state="PROBLEM" hostproblemid=0 lasthostproblemid=0 servico="Problema_TESTE01" triggerid="1111" eventzabbix="2222"
+ Calling 'glpi.test' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
+ Calling 'glpi.doLogin' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
+ Calling 'glpi.createTicket' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=14mem8sn868mot1rc2ui19hmj1
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/ack_zabbix_glpi.py", line 15, in <module>
    reconhecer_evento = conexao.event.acknowledge({"eventids": sys.argv[1], "message": "Ticket " + str(sys.argv[2]) + " criado no GLPI."})
  File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 314, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 71, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 321, in do_request
    return self.parent.do_request(req)
  File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 272, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
zabbix_api.ZabbixAPIException: (u'Error -32500: Application error., No permissions to referred object or it does not exist! while sending {"params": {"message": "Ticket 1392 criado no GLPI.", "eventids": "2222"}, "jsonrpc": "2.0", "method": "event.acknowledge", "auth": "7b441e0ed6d5ab6eda8668d0d6f67bb4", "id": 1}', -32500)
+ Calling 'glpi.doLogout' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=14mem8sn868mot1rc2ui19hmj1


FECHANDO O CHAMADO
-------------------------------------
[root@srvzabbixsina externalscripts]# php tickets_zabbix_glpi.php eventhost="Zabbix server" event="UP" state="SOLVED" hostproblemid=1 lasthostproblemid=1 servico="Problema_TESTE01" triggerid="1111" eventzabbix="2222"
+ Calling 'glpi.test' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
+ Calling 'glpi.doLogin' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
+ Calling 'glpi.addTicketFollowup' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=89r87gsqppvshqolh5q06e1mh3
+ Calling 'glpi.doLogout' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=89r87gsqppvshqolh5q06e1mh3

Pode me dar uma ajuda?

**Comment by saumyajit** [comment]
Hi Janssen,

Yea I'm able to create ticket with macro values. Thanks a ton for all your support. 

Need you help to configure below things
1) when event got cleared in zabbix, action become OK, but ack not happening (NO) for that clear event. how can make that to be acknowledged too.
2) how i can print  usage statistics (like to add some more details about the event) in description along with the existing values.
3) How can i configure ack script to ack any event based on the event id from description not from Event Title

Thanks once again... :)

**Comment by saumyajit** [comment]
Hi Janssen,

now i'm facing another issue. What ever the trigger severity is there for an event in zabbix, the ticket is getting generated with medium priority for all in glpi. PFA for details. Kindly guide, how can i print the exact trigger severity in ticket priority. (in attachment, the event is with DISASTER severity but for this ticket got generated with MEDIUM priority. this is creating some sort of confusion.)
 
![screenshot from 2016-04-29 19 51 48](https://cloud.githubusercontent.com/assets/18307963/14919039/7e5e5886-0e44-11e6-872c-2d3770cb04cf.png)

**Comment by saumyajit** [comment]
Hi Janssen,

kindly suggest....

**Comment by janssenlima** [comment]
Please open an issue for each problem.
