### ISSUE TITLE
Problema com fechamento de Ticket/Chamado no GLPI

### ISSUE THREAD

**Issue by carlosferreira1** [janssenlima/zabbix-glpi#3]
Olá Janssen,

Hoje tenho o ambiente separado em 3 servidores, conforme abaixo:

Máquina 1 - Zabbix Server:
CentOS Linux release 7.2.1511 (Core) x86_64
Zabbix 3.0.0
PHP 5.4.16

Máquina 2 - GLPI
CentOS release 6.7 (Final) x86_64
GLPI 0.9
PHP 5.4.45

Máquina 3 - MySQL
CentOS release 6.7 (Final)  x86_64
mysql-server-5.1.73-5.el6_6.x86_64

Os tickets são abertos corretamente no GLPI, porém o mesmo não fecha.

Quando executo o comando na mão, o chamado é fechado. Observe que na hora de abrir ele gera um erro, mas mesmo assim, ele abre o chamado no GLPI.
Outro detalhe, se eu colocar o STATUS como OK na mão ele não fecha o chamado. Só fecha se eu colocar o status como SOLVED.

ABRINDO O CHAMADO

[root@srvzabbixsina externalscripts]# php tickets_zabbix_glpi.php eventhost="Zabbix server" event="DOWN" state="PROBLEM" hostproblemid=0 lasthostproblemid=0 servico="Problema_TESTE01" triggerid="1111" eventzabbix="2222"

Calling 'glpi.test' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
Calling 'glpi.doLogin' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
Calling 'glpi.createTicket' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=14mem8sn868mot1rc2ui19hmj1 Traceback (most recent call last): File "/usr/lib/zabbix/externalscripts/ack_zabbix_glpi.py", line 15, in reconhecer_evento = conexao.event.acknowledge({"eventids": sys.argv[1], "message": "Ticket " + str(sys.argv[2]) + " criado no GLPI."}) File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 314, in method return self.universal("%s.%s" % (self.data["prefix"], name), opts[0]) File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 71, in wrapper return self.do_request(self.json_obj(method, opts))['result'] File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 321, in do_request return self.parent.do_request(req) File "/usr/lib/python2.7/site-packages/zabbix_api.py", line 272, in do_request raise ZabbixAPIException(msg, jobj['error']['code']) zabbix_api.ZabbixAPIException: (u'Error -32500: Application error., No permissions to referred object or it does not exist! while sending {"params": {"message": "Ticket 1392 criado no GLPI.", "eventids": "2222"}, "jsonrpc": "2.0", "method": "event.acknowledge", "auth": "7b441e0ed6d5ab6eda8668d0d6f67bb4", "id": 1}', -32500)
Calling 'glpi.doLogout' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=14mem8sn868mot1rc2ui19hmj1
FECHANDO O CHAMADO

[root@srvzabbixsina externalscripts]# php tickets_zabbix_glpi.php eventhost="Zabbix server" event="UP" state="SOLVED" hostproblemid=1 lasthostproblemid=1 servico="Problema_TESTE01" triggerid="1111" eventzabbix="2222"

Calling 'glpi.test' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
Calling 'glpi.doLogin' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php
Calling 'glpi.addTicketFollowup' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=89r87gsqppvshqolh5q06e1mh3
Calling 'glpi.doLogout' on http://glpi.sina.ssa/plugins/webservices/xmlrpc.php?session=89r87gsqppvshqolh5q06e1mh3
Pode me dar uma ajuda?

**Comment by janssenlima** [comment]
Sobre a abertura do chamado: você criou um usuário diferente para usar a API? Esse erro que aparece está relacionado a permissão. (No permissions to referred object or it does not exist!).

Verifique ao abrir um chamado, se o evento é reconhecido. Provavelmente não.

Sobre o problema ao fechar o chamado: O **_state_** eu pego do status da trigger do Zabbix: PROBLEM ou OK. Mas isso não faz diferença para fechar o chamado no GLPI. O que importa para o fechamento é o valor do parâmetro **event**, UP ou DOWN, conforme você pode observar o switch a partir da linha 109 do código PHP.

**Comment by carlosferreira1** [comment]
Como é base de teste o usuário que estou utilizando é o próprio GLPI. A abertura na linha de comando funcionou, tanto quanto o fechamento. Observe que o erro de permissão continuou aparecendo, mas o chamado ele fechou quando invoco o comando manual.

![image](https://cloud.githubusercontent.com/assets/5273422/14382653/c9376ec8-fd65-11e5-9305-8f1c1cecd7cb.png)

![image](https://cloud.githubusercontent.com/assets/5273422/14382673/ec3f74a6-fd65-11e5-908d-20d3b56a9fc9.png)

**Comment by carlosferreira1** [comment]
Zerei a base do GLPI pra refazer os testes, e alterei as permissões da pasta do pluggin Webservice. Vou testar e te dou um retorno.

**Comment by janssenlima** [comment]
A permissão que me referi é do usuário de acesso ao Zabbix no arquivo ack_zabbix_glpi.py

**Comment by janssenlima** [comment]
O erro que aparece na abertura do chamado é referente ao reconhecimento do evento no zabbix.
Repare na imagem abaixo na coluna reconhecido. Provavelmente o seu evento deve estar Não, ao invés de Sim (1).

![image](https://cloud.githubusercontent.com/assets/5981785/14383536/2500d018-fd6c-11e5-83f0-48faba8654bc.png)

**Comment by carlosferreira1** [comment]
Janssen,

O usuário do arquivo ack_zabbix_glpi.py é o Admin. Apesar do erro gerado na hora que eu executo o comando na mão ele abre, o chamado normal. E depois que eu zerei a base de dados do GLPI, ele passou a abrir e fechar chamado normalmente. 
Ou seja, seu script está 100% funcional como Centos 7 64Bit.

Vou te enviar a tela do reconhecimento de incidente. Ele está reconhecendo o incidente.

![image](https://cloud.githubusercontent.com/assets/5273422/14384229/3ceb6a40-fd70-11e5-8de7-e52533571860.png)

Muito obrigado pelo apoio. Vou fazer mais alguns testes antes de colocar em produção.

**Comment by janssenlima** [comment]
Muito bom.

Foi fechar a issue e informar sua contribuição com a homologação em CentOS 7 x86_64.

Agradeço a sua contribuição.

**Comment by alexandremundim** [comment]
Estou com problema semelhante, abre o chamado mas não fecha, ao executar manualmente o script me retorna:
root@amanda:/etc/zabbix/externalscripts# php tickets_zabbix_glpi.php 
+ Calling 'glpi.test' on http://172.16.0.126/glpi/plugins/webservices/xmlrpc.php
PHP Notice:  Undefined index: eventhost in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 40
PHP Notice:  Undefined index: event in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 41
PHP Notice:  Undefined index: state in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 42
PHP Notice:  Undefined index: hostproblemid in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 43
PHP Notice:  Undefined index: lasthostproblemid in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 44
PHP Notice:  Undefined index: servico in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 45
PHP Notice:  Undefined index: eventzabbix in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 46
PHP Notice:  Undefined index: triggerid in /usr/local/zabbix/etc/externalscripts/tickets_zabbix_glpi.php on line 47

Sabem me dizer o que pode ser?

Zabbix 3.4 com Debian 9.4 + Banco Maria DB versão 10
GLPI 9.2 com Debian 9.4 + Weservice 1.8
