### ISSUE TITLE
Issue in Zabbix-GLPI priority mapping.

### ISSUE THREAD

**Issue by saumyajit** [janssenlima/zabbix-glpi#4]
Hi Janssen,

i'm facing some issue in mapping priority. What ever the trigger severity is there for an event in zabbix, the ticket is getting generated with medium priority for all in glpi. PFA for details. Kindly guide, how can i print the exact trigger severity in ticket priority means how can i map those values with one another. (in attachment, the event is with DISASTER severity but for this ticket got generated with MEDIUM priority. this is creating some sort of confusion.).. thanks...
![7e5e5886-0e44-11e6-872c-2d3770cb04cf](https://cloud.githubusercontent.com/assets/18307963/14957452/12bcb27e-10a3-11e6-8354-e6f14bba6240.png)

**Comment by janssenlima** [comment]
This is the priority of GLPI, not the Zabbix.
Do you want to inform the priority Zabbxi in this field?

**Comment by saumyajit** [comment]
yes, i want to populate zabbix trigger severity info into GLPI priority.

**Comment by saumyajit** [comment]
Hi Janssen,

Any progress :) :)

**Comment by mcruz342** [comment]
Hi Janssen, great work. Is it possible to do this? It would be very usefull

Thanks you,
