### ISSUE TITLE
erro de acesso negado 

### ISSUE THREAD

**Issue by Alyssoncv** [janssenlima/zabbix-glpi#5]
ola amigo não consegui fazer funcionar.  e ao executar o script [root@localhost /]# php /zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="{HOSTNAME}" event="DOWN" state="{TRIGGER.STATUS}" hostproblemid=0 lasthostproblemid=0 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"
- Calling 'glpi.test' on http://localhost/glpi/plugins/webservices/xmlrpc.php
  xmlrpc error(1): Acesso negado
  [root@localhost /]# + Calling 'glpi.test' on http://localhost/glpi/plugins/webservices/xmlrpc.php
  bash: +: command not found
  [root@localhost /]# xmlrpc error(1): Acesso negado

**Comment by johnk3r** [comment]
O GLPI esta no mesmo servidor do Zabbix ? Configurou o WebServices ?

**Comment by Alyssoncv** [comment]
Sim estão no mesmo servidor. o web service 1.6 foi configurado.

**Comment by Alyssoncv** [comment]
apos refazer o tutorial novamente:: segundo erro  Access denied for user 'glpi'@'localhost' (using password: YES) in /opt/zabbix/externalscripts/tickets_zabbix_glpi.php on line 121
Access denied for user 'glpi'@'localhost' (using password: YES)[root@localhost /]

**Comment by jarffs** [comment]
Alyssoncv, você conseguiu resolver? Eu to com o mesmo problema:

 php tickets_zabbix_glpi.php  eventhost="server" event="UP" state="OK" hostproblemid=1 lasthostproblemid=1 servico="Hostname was changed on Zabbix Server" triggerid="13499" eventzabbix="142"
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
+ Calling 'glpi.test' on http://localhost/glpi/plugins/webservices/xmlrpc.php
+ Calling 'glpi.doLogin' on http://localhost/glpi/plugins/webservices/xmlrpc.php
xmlrpc error(12): Login failed (Incorrect username or password)
+ Calling 'glpi.addTicketFollowup' on http://localhost/glpi/plugins/webservices/xmlrpc.php?session=
xmlrpc error(13): Not authenticated
+ Calling 'glpi.doLogout' on http://localhost/glpi/plugins/webservices/xmlrpc.php?session=

**Comment by jarffs** [comment]
Alysson, 

Se o seu problema for o mesmo que eu tive, você edita o arquivo tickets_zabbix_glpi.php e coloca a senha correta no campo $password =     "suasenha"
