### ISSUE TITLE
Erro Fechamento do Chamado GLPI x Zabbix

### ISSUE THREAD

**Issue by andreluizmsouza** [janssenlima/zabbix-glpi#6]
Ola Janssen,
Primeira obrigado pela suas publicações, muito boas:

Estou com um problema no fechamento do CHAMADO no GLPI, conforme abaixo:
GLPI 0.90 + Zabbix 3.0 + Webservices 1.6

 php /etc/zabbix/scripts/tickets_zabbix_glpi.php eventhost="Windows 2012" event="UP" state="OK" hostproblemid=2 lasthostproblemid=2 servico="Zabbix agent on Servidor Windows 2012 is unreachable for 5 minutes" triggerid="13621" eventzabbix="5037"
- Calling 'glpi.test' on http://192.168.100.1/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.doLogin' on http://192.168.100.1/glpi/plugins/webservices/xmlrpc.php
- Calling 'glpi.addTicketFollowup' on http://192.168.100.1/glpi/plugins/webservices/xmlrpc.php?session=vk9tvmpdbnbdrl1qu75uc53br3
  xmlrpc error(14): Bad parameter (missing reopen/close option for solved ticket)
- Calling 'glpi.doLogout' on http://192.168.100.1/glpi/plugins/webservices/xmlrpc.php?session=vk9tvmpdbnbdrl1qu75uc53br3
  root@zabbix:/etc/zabbix/scripts#

**Comment by Robertolw** [comment]
Ola, encontrou uma solução para o problema?

**Comment by brungaspar** [comment]
Boa tarde! Estou com o mesmo problema, ele abre o chamado no GLPI, mas não consegue fechar o chamado.
