### ISSUE TITLE
Error creating ticket | error(14): Bad parameter (ticket)

### ISSUE THREAD

**Issue by babelattke** [janssenlima/zabbix-glpi#7]
I have Zabbix and GLPI in two different VM. 

All the configuration has been done based on the manual. however at the moment to try the command from zabbix console I'm getting the following error.

```
+ Calling 'glpi.test' on http://glpiserverip/glpi/plugins/webservices/xmlrpc.php
+ Calling 'glpi.doLogin' on http://glpiserverip/glpi/plugins/webservices/xmlrpc.php
+ Calling 'glpi.addTicketFollowup' on http://glpiserverip/glpi/plugins/webservices/xmlrpc.php?session=f2kc5s4g62aodob55p7tah84u4
xmlrpc error(14): Bad parameter (ticket)
+ Calling 'glpi.doLogout' on http://glpiserverip/glpi/plugins/webservices/xmlrpc.php?session=f2kc5s4g62aodob55p7tah84u4
```

Apparently all it's fine but it's an application bug ?

**Comment by Robertolw** [comment]
Estou enfrentando o mesmo problema.
I got the same issue.

**Comment by babelattke** [comment]
Robertolw, try it with an Admin user, I'm using "glpi".

**Comment by Robertolw** [comment]
I created a zabbix user with super-admin rights, tested with glpi user aswell and got the same error with both accounts, i can create tickets just fine with command lines and automaticaly, but i always get xmlrpc error(14): Bad parameter (ticket) when i try closing it.

**Comment by babelattke** [comment]
So your problem is only closing the ticket? if opening the ticket is working well it has to work well closing it. Check again the actions in Zabbix Server, there must be an error. 

Find below the commands I'm using in each case.

**Open**

`php /usr/lib/zabbix/externalscripts/zabbix/tickets_zabbix_glpi.php eventhost="{HOST.HOST}" event="DOWN" state="{TRIGGER.STATUS}" hostproblemid=0 lasthostproblemid=0 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"`

**Close**

`php /usr/lib/zabbix/externalscripts/zabbix/tickets_zabbix_glpi.php eventhost="{HOST.HOST}" event="UP" state="{TRIGGER.STATUS}" hostproblemid=1 lasthostproblemid=1 servico="{TRIGGER.NAME}" triggerid="{TRIGGER.ID}" eventzabbix="{EVENT.ID}"`

Both actions are configured with this parameters

Operation Type: Remote Command
Target List: Host:ZabbixServer
Type: Custom Script
Excecute on: Zabbix Agent

Hope it helps.

**Comment by Robertolw** [comment]
Hi i double checked my actions config, no luck...

```
root@Monitoramento:/home/cogeti# php /usr/lib/zabbix/externalscripts/zabbix-glpi/tickets_zabbix_glpi.php eventhost="E09 BR1 SW1" event="UP" state="OK" hostproblemid=1 lasthostproblemid=1 servico="Disponibilidade" triggerid="1512" eventzabbix="845906"
+ Calling 'glpi.test' on http://200.xxx.xxx.xxx/.../glpi/plugins/webservices/xmlrpc.php
+ Calling 'glpi.doLogin' on http://200.xxx.xxx.xxx/.../glpi/plugins/webservices/xmlrpc.php
+ Calling 'glpi.addTicketFollowup' on http://200.xxx.xxx.xxx/.../glpi/plugins/webservices/xmlrpc.php?session=96qsurhfq2oe648uuuivuh8rk1
xmlrpc error(14): Bad parameter (ticket)
+ Calling 'glpi.doLogout' on http://200.xxx.xxx.xxx/.../glpi/plugins/webservices/xmlrpc.php?session=96qsurhfq2oe648uuuivuh8rk1
```

I'm using exactly the same actions as you, the only big difference is I'm using 2 servers zabbix and glpi are running on different machines.

**Comment by prcamargo** [comment]
I have the same problem, I'm using 2 servers.

**Comment by alexandremundim** [comment]
Consegui colocar pra executar o comando remoto, me retorna executado, porém o GLPI não recebe o chamado, já está com API REST habilitado, sabem me dizer se exite algum outro detalhe?

Abrir chamado - Comando:Zabbix server:php /opt/zabbix/externalscripts/tickets_zabbix_glpi.php eventhost="BEATRIZ" event="DOWN" state="PROBLEM" hostproblemid=0 lasthostproblemid=0 servico="WSUS" triggerid="23349" eventzabbix="1902421"  - Executado

RESOLVIDO - Era o apontamento de diretório dentro de Tickets_zabbix_glpi.php estava para  /opt/zabbix/externalscripts quando deveria ser /usr/lib/zabbix/externalscripts

****************************************************************************************
Cenário:

GLPI 9.2.1 e Plugin Web Services 1.8.0 em Debian 8
Maria DB em Debian 8
Zabbix 3.4 em Debian 8
