### ISSUE TITLE
Script abre chamado somente na Entidade raiz

### ISSUE THREAD

**Issue by joseneto10** [janssenlima/zabbix-glpi#9]
Tenho instaldo o Zabbix 3.0.2 o GLPI 0.90.5 e o WebService 1.6.0. 
A instalação está ok . Quando gero o script para abrir um ticket o mesmo só abre na entidade raiz.
Trabalho na Prefeitura de Osasco e temos várias entidades.
Preciso que os problemas do Zabbix sejam abertos em uma entidade filha, mas o script tickets_zabbix_glpi.php só abre na entidade pai.
Há como automatizar isso para abrir os chamados na entidade filha?

**Comment by mausampaio** [comment]
Faz uma alteração no método createticket do arquivo tickets_zabbix_glpi.php e adiciona o campo entity e passa a entidade que deseja.

**Comment by origamaster** [comment]
dessa forma  ? : 

                                               ```
         $arg[] = "method=glpi.createTicket";
                                                        $arg[] = "entities_id=$entity";
                                                        $arg[] = "url=$xmlurl";
```
como devo chamar a entidade no script ?

**Comment by origamaster** [comment]
eu encontrei o metodo SetMyEntity no webservices do GLPI, mas como posso passar o parametro da minha entidade para o metodo ? sei q o ID da minha entidade é 2
